export const ImagePath = {
  logo: require('../assets/image/logo.png'),
  home:require('../assets/image/home.png'),
  refer:require('../assets/image/refer.png'),
  wallet:require('../assets/image/wallet.png'),
  profile:require('../assets/image/profile.png'),
  coin:require('../assets/image/coin.png'),
  ticket:require('../assets/image/ticket.png'),
  timer:require('../assets/image/Timer.png'),
  Qr:require('../assets/image/qr.png'),
  coupon:require('../assets/image/coupon.png'),
  scratch:require('../assets/image/scratch.png'),
  scratchCard:require('../assets/image/scratchCard.png'),
  voucher:require('../assets/image/voucher.png'),
  leader:require('../assets/image/leader1.png'),
  ads:require('../assets/image/ads.png'),
  ads2:require('../assets/image/ads2.png'),
};
